# Generated by Django 2.2 on 2019-06-18 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('inactive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('-description',),
            },
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbr', models.CharField(max_length=20)),
                ('inactive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('excempt', models.BooleanField(default=False)),
                ('defaults', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=60)),
                ('destination', models.CharField(max_length=60)),
                ('note', models.TextField()),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_date', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('stock_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=50)),
                ('long_description', models.TextField()),
                ('inactive', models.BooleanField(default=True)),
                ('deleted_status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.Category')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.Tax')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.ItemUnit')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('description', models.CharField(db_index=True, max_length=200)),
                ('stock_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('inactive', models.SmallIntegerField()),
                ('deleted_status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.Category')),
            ],
            options={
                'ordering': ('-description',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='dflt_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.ItemUnit'),
        ),
    ]
