# Generated by Django 2.2 on 2019-07-08 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('inve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.IntegerField()),
                ('comments', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('packed_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.SalesOrder')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.SalesOrder')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.Shipment')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.StockMaster')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.Tax')),
            ],
        ),
    ]
