# Generated by Django 2.2 on 2019-09-17 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('inactive', models.BooleanField(default=True)),
                ('vat_no', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePaymentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(max_length=50)),
                ('days_before_due', models.IntegerField()),
                ('defaults', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField()),
                ('order_reference', models.CharField(max_length=50)),
                ('invoice_reference', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.Debtor')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('defaults', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('receive_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=50)),
                ('branch', models.IntegerField()),
                ('version', models.SmallIntegerField()),
                ('reference', models.CharField(max_length=50)),
                ('customer_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('order_reference_id', models.IntegerField()),
                ('order_reference', models.CharField(max_length=200, null=True)),
                ('comments', models.TextField(blank=True, max_length=250, null=True)),
                ('order_date', models.DateTimeField()),
                ('order_type', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('deliver_to', models.CharField(blank=True, max_length=50, null=True)),
                ('from_stk_loc', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_term', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorders', to='order.Debtor')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Payment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
                ('tax', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=False, max_length=9)),
                ('default', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=False, max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default=0, max_length=50)),
                ('trans_type', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('trans_date', models.DateTimeField()),
                ('reference', models.CharField(max_length=50)),
                ('transaction_reference_id', models.IntegerField()),
                ('transfer_id', models.IntegerField()),
                ('order_reference', models.CharField(max_length=50)),
                ('note', models.TextField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ReceiveOrder')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.StockMaster')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_abrev', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.SalesType')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.StockMaster')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=50)),
                ('tax_types', models.IntegerField(null=True)),
                ('decription', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_sent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipment_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.SalesOrder')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.StockMaster')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Supplier')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.Item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.Location')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.SalesOrder')),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ReceiveOrder')),
            ],
        ),
        migrations.AddField(
            model_name='receiveorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.SalesOrder'),
        ),
        migrations.AddField(
            model_name='receiveorder',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiveorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Supplier'),
        ),
        migrations.CreateModel(
            name='PurchasesOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=200)),
                ('order_date', models.DateTimeField()),
                ('reference', models.CharField(max_length=30)),
                ('requistion_no', models.CharField(blank=True, max_length=50, null=True)),
                ('into_stock_loc', models.CharField(max_length=50)),
                ('delivery_address', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_included', models.CharField(choices=[(False, 'No'), (True, 'Yes')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('qty_invoked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('act_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('std_cost_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.Item')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.Tax')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=50)),
                ('conversion_factor', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('supplier_description', models.CharField(max_length=50)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inve.StockMaster')),
            ],
        ),
        migrations.AddField(
            model_name='debtor',
            name='sales_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.SalesType'),
        ),
    ]
