# Generated by Django 2.2 on 2019-07-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190709_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesorderdetail',
            name='tax_included',
            field=models.CharField(choices=[(False, 'No'), (True, 'Yes')], max_length=20),
        ),
    ]
