# Generated by Django 2.2 on 2019-07-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190709_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestype',
            name='tax',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
